# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mwestphall/piccolo2/piccolo2-player/piccolo2/player/player.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(780, 670)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_Status = QtGui.QWidget()
        self.tab_Status.setEnabled(True)
        self.tab_Status.setObjectName(_fromUtf8("tab_Status"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_Status)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(self.tab_Status)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(64, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.localTime = QtGui.QLabel(self.tab_Status)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localTime.sizePolicy().hasHeightForWidth())
        self.localTime.setSizePolicy(sizePolicy)
        self.localTime.setObjectName(_fromUtf8("localTime"))
        self.horizontalLayout_8.addWidget(self.localTime)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.label_6 = QtGui.QLabel(self.tab_Status)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.piccoloTime = QtGui.QLabel(self.tab_Status)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.piccoloTime.sizePolicy().hasHeightForWidth())
        self.piccoloTime.setSizePolicy(sizePolicy)
        self.piccoloTime.setObjectName(_fromUtf8("piccoloTime"))
        self.horizontalLayout_8.addWidget(self.piccoloTime)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.syncTimeButton = QtGui.QPushButton(self.tab_Status)
        self.syncTimeButton.setObjectName(_fromUtf8("syncTimeButton"))
        self.horizontalLayout_8.addWidget(self.syncTimeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gpsContainerWidget = QtGui.QWidget(self.tab_Status)
        self.gpsContainerWidget.setMinimumSize(QtCore.QSize(0, 145))
        self.gpsContainerWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.gpsContainerWidget.setObjectName(_fromUtf8("gpsContainerWidget"))
        self.layoutWidget = QtGui.QWidget(self.gpsContainerWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 740, 142))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.gpsLayoutArea = QtGui.QVBoxLayout()
        self.gpsLayoutArea.setObjectName(_fromUtf8("gpsLayoutArea"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_12.addWidget(self.label_12)
        self.gpsTime = QtGui.QLabel(self.layoutWidget)
        self.gpsTime.setObjectName(_fromUtf8("gpsTime"))
        self.horizontalLayout_12.addWidget(self.gpsTime)
        self.gpsLayoutArea.addLayout(self.horizontalLayout_12)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gpsLayoutArea.addWidget(self.label_7)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_7.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_7.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_7.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_7.addWidget(self.label_11)
        self.horizontalLayout_21.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.longitudeLabel = QtGui.QLabel(self.layoutWidget)
        self.longitudeLabel.setText(_fromUtf8(""))
        self.longitudeLabel.setObjectName(_fromUtf8("longitudeLabel"))
        self.verticalLayout_5.addWidget(self.longitudeLabel)
        self.latitudeLabel = QtGui.QLabel(self.layoutWidget)
        self.latitudeLabel.setText(_fromUtf8(""))
        self.latitudeLabel.setObjectName(_fromUtf8("latitudeLabel"))
        self.verticalLayout_5.addWidget(self.latitudeLabel)
        self.altitudeLabel = QtGui.QLabel(self.layoutWidget)
        self.altitudeLabel.setText(_fromUtf8(""))
        self.altitudeLabel.setObjectName(_fromUtf8("altitudeLabel"))
        self.verticalLayout_5.addWidget(self.altitudeLabel)
        self.speedLabel = QtGui.QLabel(self.layoutWidget)
        self.speedLabel.setText(_fromUtf8(""))
        self.speedLabel.setObjectName(_fromUtf8("speedLabel"))
        self.verticalLayout_5.addWidget(self.speedLabel)
        self.horizontalLayout_21.addLayout(self.verticalLayout_5)
        self.gpsLayoutArea.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_11.addLayout(self.gpsLayoutArea)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.gpsContainerWidget)
        self.altitudeContainerWidget = QtGui.QWidget(self.tab_Status)
        self.altitudeContainerWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.altitudeContainerWidget.setObjectName(_fromUtf8("altitudeContainerWidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.altitudeContainerWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 740, 22))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_13.addWidget(self.label_13)
        self.altimeterLabel = QtGui.QLabel(self.horizontalLayoutWidget)
        self.altimeterLabel.setText(_fromUtf8(""))
        self.altimeterLabel.setObjectName(_fromUtf8("altimeterLabel"))
        self.horizontalLayout_13.addWidget(self.altimeterLabel)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_4.addWidget(self.altitudeContainerWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.tab_Status)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.dataDir = QtGui.QLabel(self.tab_Status)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataDir.sizePolicy().hasHeightForWidth())
        self.dataDir.setSizePolicy(sizePolicy)
        self.dataDir.setObjectName(_fromUtf8("dataDir"))
        self.horizontalLayout_9.addWidget(self.dataDir)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.mountDataButton = QtGui.QPushButton(self.tab_Status)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mountDataButton.sizePolicy().hasHeightForWidth())
        self.mountDataButton.setSizePolicy(sizePolicy)
        self.mountDataButton.setObjectName(_fromUtf8("mountDataButton"))
        self.horizontalLayout_9.addWidget(self.mountDataButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        spacerItem5 = QtGui.QSpacerItem(20, 463, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab_Status, _fromUtf8(""))
        self.tab_Record = QtGui.QWidget()
        self.tab_Record.setAutoFillBackground(True)
        self.tab_Record.setObjectName(_fromUtf8("tab_Record"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_Record)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.integrationTimeView = QtGui.QTableView(self.tab_Record)
        self.integrationTimeView.setObjectName(_fromUtf8("integrationTimeView"))
        self.verticalLayout.addWidget(self.integrationTimeView)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.tab_Record)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.outputDir = QtGui.QLineEdit(self.tab_Record)
        self.outputDir.setStatusTip(_fromUtf8(""))
        self.outputDir.setObjectName(_fromUtf8("outputDir"))
        self.horizontalLayout_5.addWidget(self.outputDir)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.tab_Record)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.repeatMeasurements = QtGui.QSpinBox(self.tab_Record)
        self.repeatMeasurements.setStatusTip(_fromUtf8(""))
        self.repeatMeasurements.setMaximum(999999)
        self.repeatMeasurements.setProperty("value", 1)
        self.repeatMeasurements.setObjectName(_fromUtf8("repeatMeasurements"))
        self.horizontalLayout_3.addWidget(self.repeatMeasurements)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.infRepeat = QtGui.QCheckBox(self.tab_Record)
        self.infRepeat.setObjectName(_fromUtf8("infRepeat"))
        self.horizontalLayout_6.addWidget(self.infRepeat)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.tab_Record)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.delayMeasurements = QtGui.QDoubleSpinBox(self.tab_Record)
        self.delayMeasurements.setStatusTip(_fromUtf8(""))
        self.delayMeasurements.setObjectName(_fromUtf8("delayMeasurements"))
        self.horizontalLayout_4.addWidget(self.delayMeasurements)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkAutoIntegrate = QtGui.QCheckBox(self.tab_Record)
        self.checkAutoIntegrate.setObjectName(_fromUtf8("checkAutoIntegrate"))
        self.horizontalLayout_10.addWidget(self.checkAutoIntegrate)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.label_71 = QtGui.QLabel(self.tab_Record)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.horizontalLayout_10.addWidget(self.label_71)
        self.autoIntegrateTimeout = QtGui.QDoubleSpinBox(self.tab_Record)
        self.autoIntegrateTimeout.setMaximum(3600.0)
        self.autoIntegrateTimeout.setProperty("value", 30.0)
        self.autoIntegrateTimeout.setObjectName(_fromUtf8("autoIntegrateTimeout"))
        self.horizontalLayout_10.addWidget(self.autoIntegrateTimeout)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.previewButton = QtGui.QPushButton(self.tab_Record)
        self.previewButton.setObjectName(_fromUtf8("previewButton"))
        self.horizontalLayout_2.addWidget(self.previewButton)
        self.startRecordingButton = QtGui.QPushButton(self.tab_Record)
        self.startRecordingButton.setStatusTip(_fromUtf8(""))
        self.startRecordingButton.setObjectName(_fromUtf8("startRecordingButton"))
        self.horizontalLayout_2.addWidget(self.startRecordingButton)
        self.pauseRecordingButton = QtGui.QPushButton(self.tab_Record)
        self.pauseRecordingButton.setStatusTip(_fromUtf8(""))
        self.pauseRecordingButton.setCheckable(False)
        self.pauseRecordingButton.setObjectName(_fromUtf8("pauseRecordingButton"))
        self.horizontalLayout_2.addWidget(self.pauseRecordingButton)
        self.autoButton = QtGui.QPushButton(self.tab_Record)
        self.autoButton.setObjectName(_fromUtf8("autoButton"))
        self.horizontalLayout_2.addWidget(self.autoButton)
        self.darkButton = QtGui.QPushButton(self.tab_Record)
        self.darkButton.setObjectName(_fromUtf8("darkButton"))
        self.horizontalLayout_2.addWidget(self.darkButton)
        self.stopRecordingButton = QtGui.QPushButton(self.tab_Record)
        self.stopRecordingButton.setStatusTip(_fromUtf8(""))
        self.stopRecordingButton.setObjectName(_fromUtf8("stopRecordingButton"))
        self.horizontalLayout_2.addWidget(self.stopRecordingButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_Record, _fromUtf8(""))
        self.tab_Spectra = QtGui.QWidget()
        self.tab_Spectra.setAutoFillBackground(True)
        self.tab_Spectra.setObjectName(_fromUtf8("tab_Spectra"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_Spectra)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.spectraPlot = SpectraPlot(self.tab_Spectra)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectraPlot.sizePolicy().hasHeightForWidth())
        self.spectraPlot.setSizePolicy(sizePolicy)
        self.spectraPlot.setObjectName(_fromUtf8("spectraPlot"))
        self.verticalLayout_2.addWidget(self.spectraPlot)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.selectSpectrumButton = QtGui.QPushButton(self.tab_Spectra)
        self.selectSpectrumButton.setObjectName(_fromUtf8("selectSpectrumButton"))
        self.verticalLayout_6.addWidget(self.selectSpectrumButton)
        self.showLatest = QtGui.QCheckBox(self.tab_Spectra)
        self.showLatest.setObjectName(_fromUtf8("showLatest"))
        self.verticalLayout_6.addWidget(self.showLatest)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_14 = QtGui.QLabel(self.tab_Spectra)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_14.addWidget(self.label_14)
        self.displayUnits = QtGui.QComboBox(self.tab_Spectra)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayUnits.sizePolicy().hasHeightForWidth())
        self.displayUnits.setSizePolicy(sizePolicy)
        self.displayUnits.setObjectName(_fromUtf8("displayUnits"))
        self.displayUnits.addItem(_fromUtf8(""))
        self.displayUnits.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.displayUnits)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.downloadSimple = QtGui.QCheckBox(self.tab_Spectra)
        self.downloadSimple.setChecked(True)
        self.downloadSimple.setObjectName(_fromUtf8("downloadSimple"))
        self.verticalLayout_8.addWidget(self.downloadSimple)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.selectSpectrometer = QtGui.QComboBox(self.tab_Spectra)
        self.selectSpectrometer.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.selectSpectrometer.setObjectName(_fromUtf8("selectSpectrometer"))
        self.verticalLayout_9.addWidget(self.selectSpectrometer)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.selectShutter = QtGui.QComboBox(self.tab_Spectra)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectShutter.sizePolicy().hasHeightForWidth())
        self.selectShutter.setSizePolicy(sizePolicy)
        self.selectShutter.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.selectShutter.setObjectName(_fromUtf8("selectShutter"))
        self.horizontalLayout_15.addWidget(self.selectShutter)
        self.selectSpectrum = QtGui.QComboBox(self.tab_Spectra)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSpectrum.sizePolicy().hasHeightForWidth())
        self.selectSpectrum.setSizePolicy(sizePolicy)
        self.selectSpectrum.setObjectName(_fromUtf8("selectSpectrum"))
        self.horizontalLayout_15.addWidget(self.selectSpectrum)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_Spectra, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Schedule = QtGui.QMenu(self.menubar)
        self.menu_Schedule.setObjectName(_fromUtf8("menu_Schedule"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Connect = QtGui.QAction(MainWindow)
        self.action_Connect.setObjectName(_fromUtf8("action_Connect"))
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.actionList_Schedules = QtGui.QAction(MainWindow)
        self.actionList_Schedules.setObjectName(_fromUtf8("actionList_Schedules"))
        self.action_Add_Schedule = QtGui.QAction(MainWindow)
        self.action_Add_Schedule.setObjectName(_fromUtf8("action_Add_Schedule"))
        self.actionSave_Plot = QtGui.QAction(MainWindow)
        self.actionSave_Plot.setObjectName(_fromUtf8("actionSave_Plot"))
        self.menu_File.addAction(self.action_Connect)
        self.menu_File.addAction(self.actionSave_Plot)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Schedule.addAction(self.action_Add_Schedule)
        self.menu_Schedule.addAction(self.actionList_Schedules)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Schedule.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_4.setText(_translate("MainWindow", "Local Time", None))
        self.localTime.setText(_translate("MainWindow", "TextLabel", None))
        self.label_6.setText(_translate("MainWindow", "Piccolo Time", None))
        self.piccoloTime.setText(_translate("MainWindow", "TextLabel", None))
        self.syncTimeButton.setText(_translate("MainWindow", "sync", None))
        self.label_12.setText(_translate("MainWindow", "GPS Time ", None))
        self.gpsTime.setText(_translate("MainWindow", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow", "Piccolo GPS Location", None))
        self.label_8.setText(_translate("MainWindow", "    Longitude: ", None))
        self.label_9.setText(_translate("MainWindow", "    Latitude:", None))
        self.label_10.setText(_translate("MainWindow", "    Altitude:", None))
        self.label_11.setText(_translate("MainWindow", "    Speed:", None))
        self.label_13.setText(_translate("MainWindow", "Altimeter Altitude:", None))
        self.label_5.setText(_translate("MainWindow", "Data Directory", None))
        self.dataDir.setText(_translate("MainWindow", "TextLabel", None))
        self.mountDataButton.setText(_translate("MainWindow", "mount data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Status), _translate("MainWindow", "Status", None))
        self.label.setText(_translate("MainWindow", "Output", None))
        self.outputDir.setToolTip(_translate("MainWindow", "output directory", None))
        self.outputDir.setText(_translate("MainWindow", "spectra", None))
        self.label_2.setText(_translate("MainWindow", "Repeat", None))
        self.repeatMeasurements.setToolTip(_translate("MainWindow", "number of measurements - 0 for indefinite repeats", None))
        self.infRepeat.setText(_translate("MainWindow", "Repeat Indefinitely", None))
        self.label_3.setText(_translate("MainWindow", "Delay (sec)", None))
        self.delayMeasurements.setToolTip(_translate("MainWindow", "delay in seconds between measurements", None))
        self.checkAutoIntegrate.setText(_translate("MainWindow", "autoIntegrate", None))
        self.label_71.setText(_translate("MainWindow", "Timeout (sec)", None))
        self.previewButton.setText(_translate("MainWindow", "Preview", None))
        self.startRecordingButton.setToolTip(_translate("MainWindow", "start data acquisition", None))
        self.startRecordingButton.setText(_translate("MainWindow", "Start", None))
        self.pauseRecordingButton.setToolTip(_translate("MainWindow", "pause data acquisition", None))
        self.pauseRecordingButton.setText(_translate("MainWindow", "Pause", None))
        self.autoButton.setText(_translate("MainWindow", "Auto", None))
        self.darkButton.setText(_translate("MainWindow", "Rec Dark", None))
        self.stopRecordingButton.setToolTip(_translate("MainWindow", "stop data acquisition", None))
        self.stopRecordingButton.setText(_translate("MainWindow", "Stop", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Record), _translate("MainWindow", "Record", None))
        self.selectSpectrumButton.setText(_translate("MainWindow", "Select Spectrum", None))
        self.showLatest.setText(_translate("MainWindow", "View Realtime", None))
        self.label_14.setText(_translate("MainWindow", "Display Units:", None))
        self.displayUnits.setItemText(0, _translate("MainWindow", "Saturation %", None))
        self.displayUnits.setItemText(1, _translate("MainWindow", "DN Count", None))
        self.downloadSimple.setText(_translate("MainWindow", "Download Compressed Spectra", None))
        self.selectShutter.setToolTip(_translate("MainWindow", "select shutter", None))
        self.selectSpectrum.setToolTip(_translate("MainWindow", "select spectrum", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Spectra), _translate("MainWindow", "Spectra", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Schedule.setTitle(_translate("MainWindow", "&Schedule", None))
        self.action_Connect.setText(_translate("MainWindow", "&Connect", None))
        self.action_Connect.setStatusTip(_translate("MainWindow", "connect to remote piccolo server", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_Quit.setStatusTip(_translate("MainWindow", "exit application", None))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionList_Schedules.setText(_translate("MainWindow", "&List Schedules", None))
        self.actionList_Schedules.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.action_Add_Schedule.setText(_translate("MainWindow", "&Add Schedule", None))
        self.action_Add_Schedule.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.actionSave_Plot.setText(_translate("MainWindow", "Save &Plot", None))
        self.actionSave_Plot.setShortcut(_translate("MainWindow", "Ctrl+S", None))

from SpectraPlot import SpectraPlot
